---
driver_plugin: docker

driver_config:
  socket: <%= ENV['DOCKER_HOST'] || 'unix:///var/run/docker.sock' %>

provisioner:
  name: chef_zero
  provision_command:
  - apt-get install -y net-tools

platforms:
- name: ubuntu-12.04

suites:
- name: default
  run_list: 
    - recipe[mycookbook::nginx]
